Public NotInheritable Class AboutBox23

    Private Sub AboutBox23_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        AboutBox1.Close()
        AboutBox3.Close()
        AboutBox5.Close()
        AboutBox7.Close()
        AboutBox8.Close()
        AboutBox9.Close()
        AboutBox11.Close()
        AboutBox12.Close()
        AboutBox13.Close()
        AboutBox14.Close()
        AboutBox15.Close()
        AboutBox16.Close()
        AboutBox17.Close()
        AboutBox18.Close()
        AboutBox19.Close()
        AboutBox20.Close()
        AboutBox21.Close()
        AboutBox22.Close()
        Form1.Close()
        form1Pad.Close()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form31.Close()
        Form32.Close()
        Form34.Close()
        Form35.Close()
        Form36.Close()
        Form37.Close()
        Form38.Close()
        Form39.Close()
        Form40.Close()
        Form41.Close()
        Form42.Close()
        Form43.Close()
        Form44.Close()
        Form45.Close()
        Form46.Close()
        Close()
    End Sub

    Private Sub OKButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub

End Class
